# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test
  displayName: "Running Tests to verify that everything works as expected"
  jobs:  
  - job: Test
    displayName: "Setting up the environment"
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
      continueOnError: false

    - script: |
        npm install
        npm run test
      displayName: 'npm install and test'
      
- stage: Build
  displayName: "Building the Application"
  jobs:
  - job: Build
    displayName: "Buildign the Î‘pplication"
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      continueOnError: false
    - script: |
        npm install
        npm run build
      displayName: 'Installing and building the application'

    - task: CmdLine@2
    - script: |
        rm -r node_modules
      displayName: 'remove node_modules'

    - task: CmdLine@2
    - script: |
        npm install --only=prod
      displayName: 'Instal only essential modules that required on prod'

    - task: ArchiveFiles@2
      displayName: 'Archive $(Build.SourcesDirectory)'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'

  
